name: Update Once Human Mods Data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install requests beautifulsoup4
      - run: python update_data.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Automated update of data.json"

      - name: Push using PAT
        run: git push https://$PAT_TOKEN@github.com/Vitaliy26rus/once-human-mods.git HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}